### ISSUE TITLE
fix: step type in autoreset wrapper

### ISSUE THREAD

**Issue by dluo96** [instadeepai/jumanji#106]
### Is your feature request related to a problem? Please describe
When using `AutoResetWrapper`, the sequence of `timestep.step_type` returned during a rollout shows 0 values where the env has been auto reset instead of 2 values. Recall that

- 0 corresponds to the first step
- 1 corresponds to a mid step
- 2 corresponds to the last step

### Describe the solution you'd like
Move the auto reset bug: `[1, 1, 1, 2, 0, 1, 1, 1]` has to be converted to `[1, 1, 1, X, 1, 1, 1]` with X being 0 or 2. Right now it is 0 but it should be 2 to warn the user that the episode got terminated. This would be important e.g. if using `while not timestep.last()`. 

```
timestep = timestep.replace(  # type: ignore
    observation=reset_timestep.observation
)
```

**Comment by clement-bonnet** [comment]
Got fixed in #123
