### ISSUE TITLE
docs: mention request for Pgx

### ISSUE THREAD

**Issue by sotetsuk** [instadeepai/jumanji#107]
Sorry for the comment from out of the blue. Jumanji's sophisticated API is great, and its application to problems like TSP is really interesting.

Today, we released [Pgx](https://github.com/sotetsuk/pgx), a collection of JAX-based RL environments dedicated to classic board games like Go. We have implemented over 15 environments, including Backgammon, Shogi, and Go, and confirmed that they are considerably faster than existing C++/Python implementations. We also plan to implement Chess and Contract Bridge in the coming weeks.

We believe Jumanji and Pgx can complement each other as both implement JAX-based RL environments but focus on different domains. We would be happy if you could kindly mention Pgx in the README like other JAX-based RL environments if you like it. For example,

> 🎲 [Pgx](https://github.com/sotetsuk/pgx) provides classic board game environments like Backgammon, Shogi, and Go.

```
🎲 [Pgx](https://github.com/sotetsuk/pgx) provides classic board game environments like Backgammon, Shogi, and Go.
```

Thanks!

**Comment by dluo96** [comment]
Hey @sotetsuk! Thank you for raising this issue! Pgx sounds awesome - just checked out your repo and it looks super cool! Re mentioning Pgx in the README, we can absolutely do that! 🚀 We have created a PR for it #108 😄

**Comment by sotetsuk** [comment]
Thank you for your quick response and comments on Pgx! 🙏
