### ISSUE TITLE
Example Notebook

### ISSUE THREAD

**Issue by noahdenicola** [instadeepai/jumanji#162]
### Is your feature request related to a problem? Please describe
Not a major issue but would be nice to have a clear example of how to use the Jumanji API.

### Describe the solution you'd like
An example notebook containing: 
- the basic usage of the Jumanji API
- how to train an RL agent on a Jumanji Environment
- rollout the agent and visualise its behaviour  

### Describe alternatives you've considered
N/A

### Additional context
N/A

---
### Misc
- [ ] Check for duplicate requests.

**Comment by sash-a** [comment]
Duplicate
