### ISSUE TITLE
The problem with graph coloring

### ISSUE THREAD

**Issue by Wendyuf** [instadeepai/jumanji#237]
I was wondering the performance shown in the paper related to graph coloring. It seems it stucked in local minimum?

**Comment by clement-bonnet** [comment]
Hi @Wendyuf, the optimal return for GraphColoring is not known. Therefore, it is not easy to judge the expected quality of the solution by simply looking at the return. Rendering a few episodes or checking training the agent on a few well-known instances might help characterize its performance.
Hope this helps!

**Comment by clement-bonnet** [comment]
I hope this answers your question! I'm going to close this for now but feel free to reopen if anything is unclear.
Thanks.
