### ISSUE TITLE
[question] Theoretical bound for the Connector env

### ISSUE THREAD

**Issue by ashok-arora** [instadeepai/jumanji#238]
Hey, 
Is there a theoretical bound on the Connector env that the solution will _always_ exist (even if suboptimal) for the agents such that there's no overlapping paths?

**Comment by ashok-arora** [comment]
Hi @clement-bonnet,
Thank you for the quick reply. I found the generators [here](https://github.com/instadeepai/jumanji/blob/main/jumanji/environments/routing/connector/generator.py) but wasn't able to find the `ratio_connections` metric, is it in a seperate place? 
Also, I was wondering if it makes sense to penalise the agent for the episode if the solvability is not guaranteed?

**Comment by clement-bonnet** [comment]
`ratio_connections` is returned as an `extras` metric inside the `timestep` object which is the output of the `reset` or `step` function. The ratio is computed as part of the environment dynamics in [here](https://github.com/instadeepai/jumanji/blob/main/jumanji/environments/routing/connector/env.py#L282).

Regarding the reward, you may implement the reward you wish [here](https://github.com/instadeepai/jumanji/blob/main/jumanji/environments/routing/connector/reward.py). The dense reward formulation which is already implemented gives a small penalty per timestep, encouraging fast wiring. Indeed, when the instance is not solvable, the penalty will be given at each timestep until the horizon is reached. Although I don't think this is a problem, it does make more sense to combine this reward with a solvable generator. I would recommend using the solvable generator (`RandomWalkGenerator`). Hope this answers your question.

**Comment by ashok-arora** [comment]
Thank you so much for the response Clement. Lastly, was the `connector` env introduced in the jumanji paper or is there any precursor to it?

**Comment by sash-a** [comment]
Hey @ashok-arora I implemented this a while ago, but I'm not aware of any previous environment that this is based on. It was just meant to be a very simple PCB routing env

**Comment by clement-bonnet** [comment]
I'm closing this as it seems to be resolved.
