### ISSUE TITLE
How can i render the env when training?

### ISSUE THREAD

**Issue by Wendyuf** [instadeepai/jumanji#242]
How can i render the env when training?

**Comment by Wendyuf** [comment]
How can i render the env when testing, better to save as a gift?

**Comment by clement-bonnet** [comment]
Hi @Wendyuf,
There is a notebook in the examples folder where you can see how to animate an environment given a list of states. You can then save the animation as a GIF for instance.
Please let me know if you have any questions regarding this.
https://github.com/instadeepai/jumanji/blob/main/examples/load_checkpoints.ipynb

**Comment by Wendyuf** [comment]
> Hi @Wendyuf, There is a notebook in the examples folder where you can see how to animate an environment given a list of states. You can then save the animation as a GIF for instance. Please let me know if you have any questions regarding this. https://github.com/instadeepai/jumanji/blob/main/examples/load_checkpoints.ipynb

Thank you, it helps

**Comment by clement-bonnet** [comment]
Great! In this case, I will close the issue. But please reopen if you have questions.
