### ISSUE TITLE
docs: make contributing link and menu bar shortcut work on the doc

### ISSUE THREAD

**Issue by clement-bonnet** [instadeepai/jumanji#25]
### Is your feature request related to a problem? Please describe
On the [documentation website](https://instadeepai.github.io/jumanji/), there are hyperlinks/shortcuts that do not work properly, although they are working on the readme on GitHub.

### Describe the solution you'd like
Clicking the shortcuts on the menu bar (Installation | Quickstart | ... | Reference Docs) should redirect the user to the corresponding locations on the page. There is a problem with the emojis that are sometimes part of the link (on the GitHub's readme I think) and sometimes not (on the website I believe). Also, the "[contributing guidelines](https://instadeepai.github.io/jumanji/#contributing:~:text=contributing%20guidelines)" link does not work on the website because there is no page hosted for it.

### Additional context
It seems that one has to reconcile the way GitHub renders the readme and the way mkdocs builds the doc when it comes to hyperlinks.

**Comment by NevilleMthw** [comment]
Is this issue currently being worked on?

**Comment by clement-bonnet** [comment]
Hello @NevilleMthw, no solution has been found for this issue yet as the current PR does not resolve the discrepancy between how GitHub and mdocks handle emojis. Please, feel free to propose a solution if you have one.

Thank you and have a great day!
