### ISSUE TITLE
Support for Multi-Dimensional Discrete Spec 

### ISSUE THREAD

**Issue by thomashirtz** [instadeepai/jumanji#257]
#### **Is your feature request related to a problem? Please describe.**

Currently, `DiscreteArray` only supports scalar values, making it challenging to define multi-dimensional discrete action spaces with specified shapes.

#### **Describe the solution you'd like**

A discrete spec similar to `BoundedArray` that accepts a `shape` parameter and allows each element within the specified shape to take on discrete values. This would enable easier handling of grid-based or multi-dimensional discrete action spaces.

#### **Misc**
- [ ] Check for duplicate requests.

**Comment by clement-bonnet** [comment]
Hi Thomas,
Would the `MultiDiscreteArray` spec work for your use case?
See e.g. how it is used in `BinPack`: https://github.com/instadeepai/jumanji/blob/main/jumanji/environments/packing/bin_pack/env.py#L264
Let me know if this helps,
Clément

**Comment by thomashirtz** [comment]
Oh, I didn't see that you use the shape of `num_values`, I thought it was a scalar.
Yes that would fit my need I believe
(The argument name is a little bit misleading no ?)
Thanks for the quick help !
