### ISSUE TITLE
bug: how to set the GPU_ID? 

### ISSUE THREAD

**Issue by zhumingpassional** [instadeepai/jumanji#267]
### Description

how to set the GPU_ID so that the gpu can be selected?

### What Jumanji version are you using?

v1.1

### Which accelerator(s) are you using?

GPU

### Additional System Info

ubuntu 20

### Additional Context

thanks .

### (Optional) Suggestion

set  GPU_ID  as a param

**Comment by sash-a** [comment]
Hi @zhumingpassional please refer to the [JAX documentation](https://jax.readthedocs.io/en/latest/installation.html) for installing the GPU version of JAX (`pip install jax[cuda12]`). If you install the correct version then you will need to use `device_put` to place data on the correct devices which will then allow your `jit` compiled functions to run on those devices. [Here](https://jax.readthedocs.io/en/latest/_autosummary/jax.device_put.html) and [here](https://jax.readthedocs.io/en/latest/faq.html#faq-data-placement) are the relevant docs for that.
