### ISSUE TITLE
fix: link to contributing markdown is broken in the documentation

### ISSUE THREAD

**Issue by cemlyn007** [instadeepai/jumanji#37]
### Description

If you go to: [https://instadeepai.github.io/jumanji/#contributing](https://instadeepai.github.io/jumanji/#contributing)

And click on [contributing guidelines](https://instadeepai.github.io/CONTRIBUTING.md) the server will return a 404.

**Comment by cemlyn007** [comment]
Related to #29.

**Comment by clement-bonnet** [comment]
Related to #25

**Comment by sash-a** [comment]
Seems to have been fixed by updating mkdocs
