### ISSUE TITLE
style: move root files to their own folder

### ISSUE THREAD

**Issue by dluo96** [instadeepai/jumanji#89]
### Is your feature request related to a problem? Please describe
The root is quite messy with lots of files (e.g. `commitlint.config.js`, `mkdocs.yml`, `license_header.txt`).

### Describe the solution you'd like
We could move a lot of these files to separate folders and keep only necessary files in the root directory (e.g. `README`, and `setup.py`).

**Comment by sash-a** [comment]
This is a pretty common practice, I don't think it is worth the effort to deviate from it
