### ISSUE TITLE
feat: use future annotations for same class type

### ISSUE THREAD

**Issue by dluo96** [instadeepai/jumanji#95]
### Is your feature request related to a problem? Please describe
This issue is about cleaning the type hinting in the repository. Currently, when a method (inside a given class) returns an object whose type is the class itself (e.g. in `Environment`), the return type is given with quotes: 
```
class Environment:

    ...

    def unwrapped(self) -> "Environment":
        ...
```
According to [this thread](https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class), this is needed for Python<3.7, but can be removed with future annotations from Python 3.7+.

### Describe the solution you'd like
Since Jumanji supports Python>=3.8, we could get rid of these quotes throughout the repository and use future annotations instead.

**Comment by dantp-ai** [comment]
I can take this as a first issue :).
