### ISSUE TITLE
feat(specs): make environment specs properties instead of methods

### ISSUE THREAD

**Issue by dluo96** [instadeepai/jumanji#98]
### Is your feature request related to a problem? Please describe
`env.observation_spec` is a method and creates a new spec each time it is being called. If we it a property, we can JIT a function that gets these specs.

### Describe the solution you'd like
```
def __init__(self):
    self.observation_spec = self._make_observation_spec()

def _make_observation_spec():
    return spec.Spec(...)
```

**Comment by aar65537** [comment]
I have also run into this issue when attempting to reference specs from a jitted function. I think a slightly better solution would be to make the property private and access it with a method.
```
def __init__(self):
    self._observation_spec = self._make_observation_spec()

@property
def observation_spec(self):
    return self._observation_spec

def _make_observation_spec():
    return spec.Spec(...)
```
This would prevent people from accidentally setting the spec. I can implement this if you agree with this solution.
